name: Robot Framework UI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  robot-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Project_phase_2/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary

    - name: Install Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1

    - name: Run Robot Framework tests
      run: |
        cd tests/Automated_Test_Cases
        robot UI_Tests.robot
