name: UI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  robot-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary

    - name: Install Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1

    - name: Run Robot Framework tests
      run: |
        robot ./Project_phase_2/tests/Unit_Test_Cases/test.robot
