name: Run Robot Framework Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 0 1 1 *' # Run tests once a year on January 1st

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.13'

    - name: Create folder for reports
      run: mkdir reports

    - name: Run Robot Framework Tests
      run: |
        docker run \
          -v ${PWD}/reports:/opt/robotframework/reports:Z \
          -v ${PWD}/tests:/opt/robotframework/tests:Z \
          -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa" \
          --user $(id -u):$(id -g) \
          ppodgorsek/robot-framework:latest

    - name: Upload reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: reports
        path: reports
