name: Robot Framework UI Tests

on: [push, pull_request]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.13'  # Use the Python version that matches your project requirements

    - name: Install Robot Framework and SeleniumLibrary
      run: |
        pip install robotframework robotframework-seleniumlibrary

    - name: Run Robot Framework tests
      run: |
        robot -d ./results/ Project_phase_2/tests/Automated\ Test\ Cases/UI_Tests.robot
      working-directory: ${{ github.workspace }}

