name: Unit Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Project_phase_2/

    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.13
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt
          pip install werkzeug==2.3.0
          pip install coverage 

      - name: Test with coverage
        run: |
          cd tests/Unit_Test_Cases
          coverage run -m pytest Unit_Test.py
          coverage html 

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.html  # Adjust the path if needed
          fail_ci_if_error: true  # Optional: specify if CI should fail on upload error

