name: Unit Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run :
        working-directory: ./Project_phase_2/
  
    strategy:
      matrix:
        python-version: [3.10]
  
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.13
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install googletrans==4.0.0rc1
          pip install pymysql
          pip install werkzeug==2.3.0
          pip install pytest
          pip install flask                  
          pip install flask-bcrypt 
          pip install flask-login 
          pip install flask-sqlalchemy 
          pip install flask-testing 
          
      - name: Test App code
        run: |
          cd tests/Unit_Test_Cases
          pytest Unit_Test.py
          
