name: Unit Test

on:
  pull request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run :
        working-directory: ./Project_phase_2/
  
    strategy:
      matrix:
        python-version: [3.10]
  
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: $((matrix.python-version))
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install googletrans==4.0.0rc1
          pip install pymysql
          pip uninstall werkzeug
          pip install werkzeug==2.3.0
          
      - name: Test App code
        run: |
          cd tests/Unit_Test_Cases
          pytest Unit_Test.py
